default:
  image: gitlab.huma-num.fr:7443/rcarto/quartocker:20250612

create-pages:
  stage: deploy
  environment: production
  pages: true
  artifacts:
    paths:
      - public
  script:
    - quarto render
    - mkdir public
    - mv _site/* public/

